version: '3'

services:
  calendar-system:
    image: calendar
    container_name: calendar
    ports:
      - "7777:80"
    networks:
      - calendar-network
    environment:
      - TZ=Asia/Seoul
    restart: always
    depends_on:
      - calendar-db

  calendar-db:
    image: calendar-db
    container_name: calendar-db
    ports:
      - "3307:3306"
    networks:
      - calendar-network
    environment:
      - MYSQL_DATABASE=calendar
      - MYSQL_ROOT_PASSWORD=12341234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

networks:
  calendar-network:
    driver: bridge